### ISSUE TITLE
Fog (Redmi 10C) deep sleep is not working

### ISSUE THREAD

**Issue by lululoid** [eun0115/releases#1]
![Screenshot_20230111-101001_Settings](https://user-images.githubusercontent.com/42432169/211709190-b2a6ebb3-0ef7-4413-bf5a-2a51c4f6d2d3.png)
It's always an issue in a lot of ROM. It drains my battery a lot even when not in use. General user like me would thankful if deep sleep is working.

**Comment by eun0115** [comment]
> would

deep sleep in Redmi 10C is hit or miss, since it uses prebuilt kernel, i only have 2 conclusion in my mind, that its either the kernel or the source itself. i have Redmi Note 8 which it has a custom kernel and deep sleep is hit or miss as well
